### ISSUE TITLE
compact(): Undefined variable: media 

### ISSUE THREAD

**Issue by Arielblues** [BocianCZ/gallery-module#8]
I installed your gallery on asgard Version 3.6.1.

Installing and everything worked fine.

However i get the following error when trying to make a new gallery 
compact(): Undefined variable: media (View: .....\Modules\Gallery\Resources\views\admin\galleries\create.blade.php).

This has to do that asgardcms admin is mostly now done through vue.js i think

I deleted @mediaMultiple('gallery') from create.blade.php. The error is gone but i cannot create the images immedialety only when editing the gallery.

Any idea how to make it compatible with the latest way asgardcms works?

**Comment by becquerel** [comment]
@Arielblues  thanks for the report, I will take a look ... hopefully tomorrow, but it may have to wait couple weeks

**Comment by Arielblues** [comment]
Thanks! 
I looked in to the code from the page module for comparison but i have to give it a good look to understand the working.

**Comment by Arielblues** [comment]
i checked another module maker and this person made the module suitable for vue.

https://github.com/daothanh/asgard-taxonomy

**Comment by becquerel** [comment]
yep, I have one of my private modules also working in vue.js, but unfortunately I do not have time to port gallery module functionality to vue right now. Either way, even if some asgard admin modules are written in vue, it normally does not break modules that are not written in vue, they should all work, just the old "plain laravel" way, without the nice vue.js touch.

However, I am testing gallery module (3.0.1), also on asgard 3.6.1, and it all works fine for me. I can add new photos even when creating new gallery, it saves correctly.

Right now, I am not sure how to go from here. Can you maybe try to provide little more insights / specific steps on how to replicate the issue ?

**Comment by Arielblues** [comment]
Thanks for the feedback. i just reinstalled asgardcms on laragon. 
(i used xampp before, and that worked when installing asgardcms. So i thought everything worked fine. However i got a problem with installing npm so i switched to laragon).

Anyway, your module works fine indeed!

btw, do you have an plans to add some features to it?
(I am actually new to laravel. I made a multilingual site on symfony and i want to make the same on laravel). 
So in my symfony app i implemented a cropper function like https://github.com/fengyuanchen/cropperjs
I miss that in the media module. that you can crop yourself each image how you want it or in a gallery.

This is a bit offtopic. but i like the way asgardcms multilingual part works and i am checking out how easy it is to customize it.

**Comment by becquerel** [comment]
@Arielblues I actually also have simple cropper / resizer, but it is currently part of one of my proprietary modules. You are right that it probably belongs to Media module, I would have used it as well, but I don't think it exists there.

AFAIK, Asgard has a way to create specified thumbnails for each uploaded image, which is not exactly what you need, but it might work in some cases.

I might opensource my image resizer/cropper, but I need to find some spare time to do it. Unfortunately currently it is bundled with different code that I am not able to opensource

**Comment by becquerel** [comment]
closing (non-issue)

**Comment by Arielblues** [comment]
or maybe have a new module which has this feature. or like version b.
Yes the specific created thumbnails is handy but i like to recenter etc when cropping the images. 

I will look into this as well.
